### ISSUE TITLE
支持按住esc后，自动切换为英文吗？(vim)

### ISSUE THREAD

**Issue by Xwudao** [fkxxyz/rime-cloverpinyin#108]
如题，在inteilj 这类软件点vim模式中，vim模式切换与中英文模式，是件令人非常痛苦点事情。

简单来说：就是在按住esc，进入normal模式时，rime自动切换为英文，可以实现这种吗？

**Comment by myl7** [comment]
在 vim 方面有一些插件可以实现类似功能，例如 https://github.com/lilydjwg/fcitx.vim 或是 https://github.com/lyokha/vim-xkbswitch 或是 https://jdhao.github.io/2021/02/25/nvim_ime_mode_auto_switch/ 等等方案。但如果是输入法来实现这种自动切换的话，感觉这种针对某个特定软件做特殊操作优化的情况不太合适。

**Comment by Xwudao** [comment]
> 在 vim 方面有一些插件可以实现类似功能，例如 https://github.com/lilydjwg/fcitx.vim 或是 https://github.com/lyokha/vim-xkbswitch 或是 https://jdhao.github.io/2021/02/25/nvim_ime_mode_auto_switch/ 等等方案。但如果是输入法来实现这种自动切换的话，感觉这种针对某个特定软件做特殊操作优化的情况不太合适。

不是纯粹的vim，是IDE里面的vim插件，所以可能没法使用你上面说的几种方案

**Comment by myl7** [comment]
如果是 IDE 中的 vim 插件且没有（方便的）API 获取当前的 vim 模式，那应该没有实现自动切换中英文的办法？至少我不太想得到。

**Comment by Xwudao** [comment]
是的
