### ISSUE TITLE
manjaro-kde上,ibus-rime,emoji等插件无效,并未实际工作

### ISSUE THREAD

**Issue by Error996** [fkxxyz/rime-cloverpinyin#112]
![image](https://user-images.githubusercontent.com/12880110/149313969-1aa1c6db-4e4d-4fa9-9747-b4f283c3c889.png)

按照wifi方法安装ibus,并下载带bin的包解压到用户rime目录的

**Comment by Error996** [comment]
但是设置里却能正常工作
![image](https://user-images.githubusercontent.com/12880110/149314237-dcfad483-db9e-4bd2-b97f-7b618e56988f.png)

**Comment by notplus** [comment]
`opencc/emoji_word.txt`和`opencc/symbol_word.txt`里去除重复的行就可以了
