### ISSUE TITLE
小白部署问题

### ISSUE THREAD

**Issue by jiangdengke** [fkxxyz/rime-cloverpinyin#165]
在输入法下载好之后，解压文件如下图
![Snipaste_2024-06-06_15-26-57](https://github.com/fkxxyz/rime-cloverpinyin/assets/128907726/b7f0e29d-1283-4f9e-92dd-3a940193bfd8)
但是点开"输入法设定"之后并没有
![a](https://github.com/fkxxyz/rime-cloverpinyin/assets/128907726/e549befe-e280-4889-9184-3f42b1123eee)
中州韵输入法

**Comment by kimwang1978** [comment]
把clover文件夹下的所有文件拷贝到图片所在目录再试试看。

**Comment by jiangdengke** [comment]
> 把clover文件夹下的所有文件拷贝到图片所在目录再试试看。
请问图片目录是哪个，这几个文件夹我都打开看了，貌似都不是

**Comment by jiangdengke** [comment]
抱歉，我解压错了，解压的文件应该是散落在rime目录下的
