### ISSUE TITLE
能否做一个iOS上的iRime输入法输入方案

### ISSUE THREAD

**Issue by DreamAfar** [fkxxyz/rime-cloverpinyin#19]
你好，我在pc上用你方案在小狼毫，挺好用。发现iOS上有个iRime输入法，可以自行添加方案，就尝试照着app作者的帮助文档把你的输入方案添加进去，可是一直不成功。有兴趣的话研究一下，谢谢！
这是输入法作者的设置文档http://wiki.5koon.com/doku.php?id=customisation#%E5%85%AB_%E6%B7%BB%E5%8A%A0%E6%96%B0%E6%96%B9%E6%A1%88

**Comment by fkxxyz** [comment]
最主要我手头上没有现成的 iOS 设备用来测试，也没有太多的精力给手机适配，比如九宫格方案之类的，不过我有时间的话会研究研究的
