### ISSUE TITLE
放到用户文件夹后切换到这个输入法就没法用了

### ISSUE THREAD

**Issue by he426100** [fkxxyz/rime-cloverpinyin#2]
无法切换到中文打字，输入法处于残废状态
平台：windows
已经吧所有文件拷贝到AppData\Roaming\Rime

**Comment by fkxxyz** [comment]
你好，我之前还真没在 Windows 平台测试过，看到你的反馈之后，我立马亲自在32位的 Windows XP 和 64位的 Windows 7 ，下载了小狼毫进行了测试。

结果和你一样，惨不忍睹。

复制过来之后，切换到该输入法，然后开始自动部署，半分钟之后提示报错，小狼毫算法服务已停止运行，部署程序崩溃，输入法就无法使用了。

通过任务管理器找到了原因，部署的过程中，WeaselServer.exe 这个进程的内存占用飙升，飙升到大约 1.6G 的时候，程序崩溃。猜测是由于词库太大，部署的时候超过了32位的程序所能申请的最大内存，导致崩溃。

而 rime 官方没有提供 64 位版本的小狼毫，我手头也没有现成的 VS 来编译 64 位版本小狼毫，这真是个令人头痛的问题。

目前暂时的解决办法是，在 linux 端先部署好，在数据目录会生成 build 目录，把整个 build 目录也复制到 windows 的 rime 数据文件夹（要先退出算法服务才能复制成功，复制完成后手动启动小狼毫安装目录下的 weasel-0.14.3\WeaselServer.exe 或重启输入法），也就跳过了在 windows 端部署这个步骤避免了崩溃，这个解决办法测试通过。

我后续会精简词库，和在 release 上发布已经部署好的二进制 build 文件夹，并且完善在 windows 端部署的文档。

感谢你的反馈。

**Comment by he426100** [comment]
实测已解决，已顺利在windows下使用
