### ISSUE TITLE
有没有准备适配到安卓端的Trime？

### ISSUE THREAD

**Issue by sxqsfun** [fkxxyz/rime-cloverpinyin#20]
目前刚在 linux 上食用，确实真香！有没有准备适配到安卓Trime的计划？

**Comment by xwooface** [comment]
> 我已经试过了，重新部署后，输入不了中文。应该是有不兼容的地方

先在windows小狼毫部署过之后，将rime文件夹下的所有文件拷贝到手机同文输入法的rime文件夹就行了

**Comment by sxqsfun** [comment]
> > 我已经试过了，重新部署后，输入不了中文。应该是有不兼容的地方
> 
> 先在windows小狼毫部署过之后，将rime文件夹下的所有文件拷贝到手机同文输入法的rime文件夹就行了

非常感谢🙏🏻️，已经可以用了！
