### ISSUE TITLE
请问双拼是否能用？

### ISSUE THREAD

**Issue by Jacobax** [fkxxyz/rime-cloverpinyin#25]
能的话如何配置？小鹤双拼，Rime新用户，不是很懂

**Comment by ClSlaid** [comment]
https://github.com/fkxxyz/rime-cloverpinyin/issues/7#issuecomment-701865083
That may solve your problem

**Comment by Jacobax** [comment]
> [#7 (comment)](https://github.com/fkxxyz/rime-cloverpinyin/issues/7#issuecomment-701865083)
> That may solve your problem

perfectly did. thanks!
