### ISSUE TITLE
朙月拼音的用户词库怎么导入？

### ISSUE THREAD

**Issue by Hades-001** [fkxxyz/rime-cloverpinyin#26]
目前在用朙月拼音，用户词库是繁体的，有办法导入本输入法吗？

**Comment by Hades-001** [comment]
已用 OpenCC 解决

**Comment by Sciroccogti** [comment]
> 已用 OpenCC 解决

请问有具体方法么？我也遇到了这个问题～

**Comment by Hades-001** [comment]
> > 已用 OpenCC 解决
> 
> 请问有具体方法么？我也遇到了这个问题～

点击菜单栏的用户文件夹同步，会有一个用户词库的txt文件，百度下载window版的opencc，然后按照说明繁转简，转换完成后，把表头信息换成cloverpinyin的，再次点击菜单栏的用户文件夹同步即可。

**Comment by Sciroccogti** [comment]
感谢！已经成功了
