### ISSUE TITLE
切换应用时允许默认英文模式

### ISSUE THREAD

**Issue by myl7** [fkxxyz/rime-cloverpinyin#30]
使用 rime-cloverpinyin 时，切换不同应用后中英文输入模式没有保存，会默认变为中文模式。我已尝试过在 fcitx5 的配置中设置 Share Input State: All，但是没有效果。请问能否增加对此的支持呢？

环境：
Manjaro latest
fcitx5 0.0.0.20200909.1-1
rime-cloverpinyin 1.1.3-1

**Comment by fkxxyz** [comment]
一般是直接打补丁设置默认英文

https://github.com/fkxxyz/rime-cloverpinyin/wiki/issues#%E8%AE%BE%E7%BD%AE%E9%BB%98%E8%AE%A4%E8%8B%B1%E6%96%87

打补丁的方法可以看官方 rime 文档
https://github.com/rime/home/wiki/CustomizationGuide#%E5%AE%9A%E8%A3%BD%E6%8C%87%E5%8D%97
