### ISSUE TITLE
发现少个字：帧

### ISSUE THREAD

**Issue by MiraculousMoon** [fkxxyz/rime-cloverpinyin#31]
只有用cloverpinyin时候才有，换成明月之后就没问题了（

**Comment by fkxxyz** [comment]
我输入zheng的时候，会出现“帧”这个字
特意去看了下字典文件，也是有这个字

> $ cat /usr/share/rime-data/clover.base.dict.yaml | grep 帧
> 2570:帧	zheng	95823

我这也不知道你那边为什么没有，是否自定义字典了而替换掉了默认的字典？

**Comment by MiraculousMoon** [comment]
> 我输入zheng的时候，会出现“帧”这个字
> 特意去看了下字典文件，也是有这个字
> 
> > $ cat /usr/share/rime-data/clover.base.dict.yaml | grep 帧
> > 2570:帧	zheng	95823
> 
> 我这也不知道你那边为什么没有，是否自定义字典了而替换掉了默认的字典？

我手动重新导入了一下字典好了（顺便加了一些常用词）

**Comment by lianxiaochenProgram** [comment]
帧读zhēn
