### ISSUE TITLE
manjaro上emoji显示unicode编号而不是字符

### ISSUE THREAD

**Issue by qianyigengwu** [fkxxyz/rime-cloverpinyin#33]
如图：
![无标题](https://user-images.githubusercontent.com/50252868/95007725-7592d800-0645-11eb-9673-a3bbf598e3d6.png)

**Comment by qianyigengwu** [comment]
已解决，非常抱歉

**Comment by bogo-y** [comment]
同Manjaro，emoji不显示任何内容，rime-emoji已经装了，可以麻烦你说下怎么解决emoji显示问题的吗？
