### ISSUE TITLE
安装后无法输入中文

### ISSUE THREAD

**Issue by YaoLaiGang** [fkxxyz/rime-cloverpinyin#36]
如题，使用fcitx-rime安装没有问题。显示使用了该方案，但是默认没有候选框，直接输出英文字母。尝试多种快捷键仍然无效。

**Comment by YaoLaiGang** [comment]
另外切换到明月方案可以正常输入中文

**Comment by xtccc** [comment]
你切换到四叶草输入法 ，按F4 看看是不是中文输入没打开

**Comment by YaoLaiGang** [comment]
> 你切换到四叶草输入法 ，按F4 看看是不是中文输入没打开

是的，是我的问题，十分感谢
