### ISSUE TITLE
怎么修改候选词语的字体大小啊？ 不懂rime 自己修改了，不成功

### ISSUE THREAD

**Issue by xtccc** [fkxxyz/rime-cloverpinyin#39]
# 我自己这么修改了，重新部署也不行，请教下大家怎么弄？

xtcc@xtccarch:~/.local/share/fcitx5/rime $ cat default.custom.yaml                                               130 ↵
patch:
  "menu/page_size": 9
  "style/font_point": 30
  schema_list:
    - schema: clover% 
# 解释
我修改的page_size　成功了，只有这个候选字体大小不成功。
# 环境　：
archlinux   fcitx5

**Comment by fkxxyz** [comment]
我印象中fcitx5的字体大小在fcitx5的主题配置文件里有设置，所以rime的配置可能就会失效
安装 fcitx5-configtool 这个包，然后附加组件里，经典用户界面，配置，调整字体大小和主题

**Comment by xtccc** [comment]
好的，解决了，谢谢😎️
![Uploading 2020-11-09T18:47:29UTC.png…]()

**Comment by zhangboqi** [comment]
想知道ibus的怎么设置？
