### ISSUE TITLE
设定默认英文输入

### ISSUE THREAD

**Issue by yyu0378** [fkxxyz/rime-cloverpinyin#46]
我添加了四叶草输入法，原来使用的是明月输入法，配置有默认输入是英文。但该配置对于四叶草没有生效，不知道是不支持还是说要其他的设定。谢谢

**Comment by fkxxyz** [comment]
https://github.com/fkxxyz/rime-cloverpinyin/wiki/issues#%E8%AE%BE%E7%BD%AE%E9%BB%98%E8%AE%A4%E8%8B%B1%E6%96%87

switches 的序号和明月输入法不一样，看看是不是这个问题

**Comment by yyu0378** [comment]
> 
> 
> https://github.com/fkxxyz/rime-cloverpinyin/wiki/issues#%E8%AE%BE%E7%BD%AE%E9%BB%98%E8%AE%A4%E8%8B%B1%E6%96%87
> 
> switches 的序号和明月输入法不一样，看看是不是这个问题

谢谢，确实是这个问题，感谢啊
