### ISSUE TITLE
arch + fcitx5 不显示emoji？

### ISSUE THREAD

**Issue by dianlujitao** [fkxxyz/rime-cloverpinyin#50]
效果如图：
![image](https://user-images.githubusercontent.com/5774651/101775168-06949c80-3b2a-11eb-82f0-5c8b16a8526b.png)

![image](https://user-images.githubusercontent.com/5774651/101775403-655a1600-3b2a-11eb-9024-4c23ab6d760b.png)

`noto-fonts-emoji` 和 `ttf-apple-emoji` 均不显示，其他软件（如 chrome）正常。

**Comment by xtccc** [comment]
fc-cache -vf
更新下字体缓存试试

**Comment by dianlujitao** [comment]
并没有效果（

**Comment by Infinemen** [comment]
pacman -S rime-emoji

**Comment by xtccc** [comment]
https://github.com/fkxxyz/rime-cloverpinyin/issues/43  按照这个装这四个包，我就不信了，为啥不行

**Comment by dianlujitao** [comment]
> pacman -S rime-emoji



> #43 按照这个装这四个包，我就不信了，为啥不行

都装了（

**Comment by Infinemen** [comment]
men@OHALA~  pacman -Ss fcitx5 | grep installed
community/fcitx5 5.0.1-1 (fcitx5-im) [installed]
community/fcitx5-configtool 5.0.0-1 (fcitx5-im) [installed]
community/fcitx5-material-color 0.0.0.20200729-1 [installed]
community/fcitx5-qt 5.0.0-1 (fcitx5-im) [installed]
community/fcitx5-rime 5.0.0-1 [installed]

 men@OHALA~ pacman -Ss rime | grep installed 
core/perl 5.32.0-3 [installed]
community/fcitx5-rime 5.0.0-1 [installed]
community/librime 1:1.6.1-1 [installed]
community/librime-data 0.0.0.20200908-1 [installed]
community/rime-bopomofo 0.0.0.20190120-2 [installed]
community/rime-cangjie 0.0.0.20201030-1 [installed]
community/rime-emoji 0.0.0.20191102-1 [installed]
community/rime-essay 0.0.0.20201004-1 [installed]
community/rime-luna-pinyin 0.0.0.20201105-1 [installed]
community/rime-prelude 0.0.0.20200908-1 [installed]
community/rime-stroke 0.0.0.20191221-2 [installed]
community/rime-terra-pinyin 0.0.0.20201018-1 [installed]

**Comment by dianlujitao** [comment]
> men@OHALA~ pacman -Ss fcitx5 | grep installed
> community/fcitx5 5.0.1-1 (fcitx5-im) [installed]
> community/fcitx5-configtool 5.0.0-1 (fcitx5-im) [installed]
> community/fcitx5-material-color 0.0.0.20200729-1 [installed]
> community/fcitx5-qt 5.0.0-1 (fcitx5-im) [installed]
> community/fcitx5-rime 5.0.0-1 [installed]
> 
> men@OHALA~ pacman -Ss rime | grep installed
> core/perl 5.32.0-3 [installed]
> community/fcitx5-rime 5.0.0-1 [installed]
> community/librime 1:1.6.1-1 [installed]
> community/librime-data 0.0.0.20200908-1 [installed]
> community/rime-bopomofo 0.0.0.20190120-2 [installed]
> community/rime-cangjie 0.0.0.20201030-1 [installed]
> community/rime-emoji 0.0.0.20191102-1 [installed]
> community/rime-essay 0.0.0.20201004-1 [installed]
> community/rime-luna-pinyin 0.0.0.20201105-1 [installed]
> community/rime-prelude 0.0.0.20200908-1 [installed]
> community/rime-stroke 0.0.0.20191221-2 [installed]
> community/rime-terra-pinyin 0.0.0.20201018-1 [installed]

```
❯ yay -Q | grep -e fcitx -e rime
fcitx5 5.0.3-2
fcitx5-configtool 5.0.1-1
fcitx5-gtk 5.0.1-1
fcitx5-material-color 0.0.0.20200729-1
fcitx5-pinyin-moegirl-rime 20201214-1
fcitx5-qt 5.0.1-1
fcitx5-rime 5.0.2-1
librime 1:1.6.1-3
librime-data 0.0.0.20201212-1
rime-bopomofo 0.0.0.20190120-2
rime-cangjie 0.0.0.20201030-1
rime-cloverpinyin 1.1.4-2
rime-emoji 0.0.0.20191102-1
rime-essay 0.0.0.20201004-1
rime-luna-pinyin 0.0.0.20201105-1
rime-prelude 0.0.0.20201212-1
rime-stroke 0.0.0.20191221-2
rime-symbols 1.0.0-1
rime-terra-pinyin 0.0.0.20201018-1
```
好像都有

**Comment by Infinemen** [comment]
换个输入法试试？我也不清楚了，抱歉。

**Comment by Korov** [comment]
https://github.com/fkxxyz/rime-cloverpinyin/wiki/issues#emoji%E5%AD%97%E4%BD%93%E5%91%88%E6%96%B9%E5%9D%97%E7%8A%B6

**Comment by dianlujitao** [comment]
修改fontconfig后问题解决https://flammie.github.io/dotfiles/fontconfig.html

**Comment by yangp1205** [comment]
请问具体如何修改fontconfig，我在ubuntu上修改不生效

**Comment by MoetaYuko** [comment]
> 请问具体如何修改fontconfig，我在ubuntu上修改不生效

把 emoji 字体添加到 sans-serif/serif/monospace 的 list 里

**Comment by yttriumz** [comment]
> 把 emoji 字体添加到 sans-serif/serif/monospace 的 list 里

请问这是要修改哪个文件呢？是把[上面你给出的链接](https://flammie.github.io/dotfiles/fontconfig.html)里的配置放到`/etc/fonts/conf.d/68-color-emoji.conf`里吗？还是说要修改`~/.config/fontconfig/fonts.conf`呢？

**Comment by FLYyyyy2016** [comment]
> 请问这是要修改哪个文件呢？是把[上面你给出的链接](https://flammie.github.io/dotfiles/fontconfig.html)里的配置放到`/etc/fonts/conf.d/68-color-emoji.conf`里吗？还是说要修改`~/.config/fontconfig/fonts.conf`呢？

我也遇到了这个问题，按照那个链接，把hinting设置为true就可以了，~/.config/fontconfig/fonts.conf，这个目录就可以生效，参考
https://bugs.freedesktop.org/show_bug.cgi?id=104542

**Comment by madjxatw** [comment]
> 修改fontconfig后问题解决https://flammie.github.io/dotfiles/fontconfig.html

Linux 下尽是这种莫名其妙的问题...如果不是安装这个输入方案，我至今还不知道怎么解决。😄️ 2018 年提交的 issue，至今未解决，简直了。

**Comment by oodzchen** [comment]
我这儿有个更全的版本 https://github.com/oodzchen/dotfiles/blob/main/dot_config/fontconfig/fonts.conf

把上面文件复制并替换 `~/.config/fontconfig/fonts.conf` ，然后运行 `fc-cache -v`，然后关闭相关应用再重新打开就好了。当然，得保证你的电脑上已经安装了 Noto CJK 和 Noto Color Emoji 字体，也可以根据自己喜好改成别的。
