### ISSUE TITLE
yay -S rime-cloverpinyin 失败

### ISSUE THREAD

**Issue by Demo-Liu** [fkxxyz/rime-cloverpinyin#51]
:: (1/2) 正在解析 SRCINFO: rime-symbols
:: (2/2) 正在解析 SRCINFO: rime-cloverpinyin
==> 错误： Cannot find the strip binary required for object file stripping.
下载源文件时出错: rime-symbols

**Comment by Demo-Liu** [comment]
2020/12/14 错误如下

**Comment by LighghtEeloo** [comment]
You can try 
```bash
yay -Syu base-devel
```

**Comment by fkxxyz** [comment]
> 2020/12/14 执行 yay -S rime-cloverpinyin命令错误如下:
> 错误：rime-symbols: 来自 "lilac (build machine) [lilac@build.archlinuxcn.org](mailto:lilac@build.archlinuxcn.org)" 的签名是未知信任的
> :: 文件 /var/cache/pacman/pkg/rime-symbols-1.0.0-1-any.pkg.tar.zst 已损坏 (无效或已损坏的软件包 (PGP 签名)).
> 打算删除吗？ [Y/n] n
> 错误：rime-cloverpinyin: 来自 "lilac (build machine) [lilac@build.archlinuxcn.org](mailto:lilac@build.archlinuxcn.org)" 的签名是未知信任的
> :: 文件 /var/cache/pacman/pkg/rime-cloverpinyin-1.1.4-2-x86_64.pkg.tar.zst 已损坏 (无效或已损坏的软件包 (PGP 签名)).
> 打算删除吗？ [Y/n] n

看报错是缺少 archlinuxcn 的 gpg 签名

尝试安装

```shell
pacman -S archlinuxcn-keyring
```
