### ISSUE TITLE
“略”字不能输入

### ISSUE THREAD

**Issue by fratcn** [fkxxyz/rime-cloverpinyin#52]
略，lue
好像拼音错了，四叶草不能输入。明月正常。

**Comment by he426100** [comment]
lve

**Comment by fkxxyz** [comment]
如果有这个需要，可以添加 u = v 的模糊音
https://github.com/fkxxyz/rime-cloverpinyin/wiki/issues#%E6%A8%A1%E7%B3%8A%E9%9F%B3%E8%AE%BE%E7%BD%AE
