### ISSUE TITLE
输入过快，单词遗漏

### ISSUE THREAD

**Issue by Liu6972319** [fkxxyz/rime-cloverpinyin#58]
![1](https://user-images.githubusercontent.com/38235130/103979366-a2143e00-51b8-11eb-9c89-2636eea408dd.png)
akaeekkeeleeoco
![2](https://user-images.githubusercontent.com/38235130/103979519-eb648d80-51b8-11eb-9d18-6033ce44f551.png)
如图

**Comment by Liu6972319** [comment]
fcitx5

**Comment by sunwgit** [comment]
这个你应该把bug提交给输入法框架吧
