### ISSUE TITLE
需要纠正一个错误的拼音

### ISSUE THREAD

**Issue by chenzhiwei** [fkxxyz/rime-cloverpinyin#83]
【反弹】的拼音应该是`fan tan`，而词库里却是 `fan dan`，导致打不出来相关词有以下两个文件需要修改：

```
clover.phrase.dict.yaml
THUOCL_caijing.dict.yaml
```

**Comment by chenzhiwei** [comment]
还有`调`字人词语中，也有很多错误的地方，我发现没地方提交修改，于是我就把字典放到了我的仓库。

一直再电脑上用五笔，手机上用拼音，现在想尝试一下在电脑上也用拼音了。

https://github.com/chenzhiwei/rime/

**Comment by spphinslove** [comment]
上调 下调 也错了

**Comment by MaxQi** [comment]
还有「重」等不少多音字有错误。

**Comment by zhea55** [comment]
> 【反弹】的拼音应该是`fan tan`，而词库里却是 `fan dan`，导致打不出来相关词有以下两个文件需要修改：
> 
> ```
> clover.phrase.dict.yaml
> THUOCL_caijing.dict.yaml
> ```

反弹道导弹

fandan 是对的。

**Comment by leyle** [comment]
触底反弹  ->  包含两个词组，一个是“触底”，一个是“反弹”  fan tan
反弹道导弹 -> 包含两个词组，一个是“反”，一个是专有名词“弹道导弹”。 dan dao



> > 【反弹】的拼音应该是`fan tan`，而词库里却是 `fan dan`，导致打不出来相关词有以下两个文件需要修改：
> > ```
> > clover.phrase.dict.yaml
> > THUOCL_caijing.dict.yaml
> > ```
> 
> 反弹道导弹
> 
> fandan 是对的。
